// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs9sLTe6_toQAAhvBFlO0B9fVL3-8OxkU',
    appId: '1:1052527864311:web:5a35c509ee13b04a9d66f2',
    messagingSenderId: '1052527864311',
    projectId: 'happytone-a0bbe',
    authDomain: 'happytone-a0bbe.firebaseapp.com',
    storageBucket: 'happytone-a0bbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHwJak6gHH-p4qINmXxd4xZ92tLWVw3Is',
    appId: '1:1052527864311:android:2b2d6e37f63a67c09d66f2',
    messagingSenderId: '1052527864311',
    projectId: 'happytone-a0bbe',
    storageBucket: 'happytone-a0bbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC36ZCW-JvkMogSABsr849k0R70WmGWufM',
    appId: '1:1052527864311:ios:801af59f51cf9fa79d66f2',
    messagingSenderId: '1052527864311',
    projectId: 'happytone-a0bbe',
    storageBucket: 'happytone-a0bbe.appspot.com',
    iosClientId: '1052527864311-g1djfncj2osjuui9etiv7hp51e21d63j.apps.googleusercontent.com',
    iosBundleId: 'com.example.Happytone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC36ZCW-JvkMogSABsr849k0R70WmGWufM',
    appId: '1:1052527864311:ios:801af59f51cf9fa79d66f2',
    messagingSenderId: '1052527864311',
    projectId: 'happytone-a0bbe',
    storageBucket: 'happytone-a0bbe.appspot.com',
    iosClientId: '1052527864311-g1djfncj2osjuui9etiv7hp51e21d63j.apps.googleusercontent.com',
    iosBundleId: 'com.example.Happytone',
  );
}
